services:
  e-nav:
    image: ecouus/e-nav:latest
    container_name: e-nav
    ports:
      - "801:1239"
    volumes:
      - ./data:/app/data
      - ./templates:/app/templates
    restart: unless-stopped
